### ISSUE TITLE
Make an authorization plugin/middleware for kubernetes (k8s)

### ISSUE THREAD

**Issue by hsluoyz** [casbin/k8s-authz#2]
Kubernetes is one of the biggest project in Go and we have no reason for not supporting it well. I hope we can develop a middleware or something similar to help Kubernetes user use Casbin as the authorization layer.

This is very important for us. Currently, no single k8s and its ecosystem users use Casbin because we don't have such a middleware.

Here's a link about how other projects integrate with k8s: https://www.openpolicyagent.org/docs/v0.12.2/kubernetes-admission-control/

We already have [some code](https://github.com/casbin/k8s-authz-archived) and even [some docs](https://github.com/casbin/k8s-authz-archived/blob/master/%E5%9F%BA%E4%BA%8E%20kubernetes%20%E6%9E%84%E5%BB%BA%E4%BA%91%E5%8E%9F%E7%94%9F%E5%88%86%E5%B8%83%E5%BC%8F%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%E5%BA%94%E7%94%A8-%E4%B8%A5%E7%81%8F-%E4%B8%AD%E6%9C%9F%E6%8A%A5%E5%91%8A.md) last summer.

Now we want to resurrect this project. Hope someone can work on it.

**Comment by divy9881** [comment]
Yes, sure I want to work on this.

**Comment by noaryan** [comment]
@hsluoyz Do we want to achieve something like Dynamic Admission Control as mentioned [here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/).

**Comment by hsluoyz** [comment]
@aryan828 yes, that's it!
