### ISSUE TITLE
Add this k8s-authz middleware to the official list

### ISSUE THREAD

**Issue by hsluoyz** [casbin/k8s-authz#22]
We have several options to integrate this repo into the kubernetes ecosystem, like code integration, listing in the 3rd-party authorization middleware list, etc. See how we did it for apisix middleware: casbin-lua/apisix-authz#5

**Comment by hsluoyz** [comment]
@ashish493

**Comment by ashish493** [comment]
@hsluoyz , I had created an issue here :- https://github.com/kubernetes/kubernetes/issues/104354

I will further contact their slack channel for more info.

**Comment by hsluoyz** [comment]
@ashish493 is there a Slack link?

**Comment by ashish493** [comment]
Yes, here's the slack link :- https://kubernetes.slack.com/messages/sig-auth
