### ISSUE TITLE
link 404 error

### ISSUE THREAD

**Issue by zhenglin-charlie-li** [casbin/k8s-authz#30]
![image](https://user-images.githubusercontent.com/63448884/211188097-45150adc-dc08-47c5-ad70-239ecc5d58b4.png)
![image](https://user-images.githubusercontent.com/63448884/211188153-2b1f519d-d2a7-4291-838f-b5682fa46ceb.png)

![image](https://user-images.githubusercontent.com/63448884/211188110-b1f34835-4575-4c4e-be49-b00a3dd7d34e.png)

**Comment by nomeguy** [comment]
fixed
