### ISSUE TITLE
1 dispatcher.go:129] Failed calling webhook, failing open casbin.default.svc: failed calling webhook "casbin.default.svc": Post "https://casbin.default.svc:443/validate?timeout=5s": x509: certificate is not valid for any names, but wanted to match casbin.default.svc

### ISSUE THREAD

**Issue by testwill** [casbin/k8s-authz#32]

**Comment by PokIsemaine** [comment]
@ Thanks for your feedback, I want to check if you are using Windows platform and execute sh script via Git Bash?

**Comment by testwill** [comment]
I am executing it under the Linux environment

**Comment by PokIsemaine** [comment]
@testwill 
Did anything unusual happen to you during the execution of gen_cert.sh?
Please check it out and take screenshots for feedback：
```
ls k8s-authz
ls k8s-authz/certs
kubectl get all
kubectl get secret 
```

**Comment by testwill** [comment]
I have no environment, I will close this issue
